include: package:lints/recommended.yaml

linter:
  rules:
    omit_local_variable_types: false
    file_names: true
    type_annotate_public_apis: true
    prefer_relative_imports: true
    directives_ordering: true
    # public_member_api_docs: false%
analyzer:
  errors:
    undefined_prefixed_name: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
