name: store_camera_template
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  contract:
    path: ../contract

  store_camera_widget:
    path: ../store_camera_widget

  intl: ^0.17.0
  rxdart: ^0.27.3
  go_router: ^3.0.7
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
