name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  build: ^2.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  csv: ^5.0.0
  dart_style: ^2.0.0
  flutter:
    sdk: flutter
  flutter_sheet_localization:
    git:
      url: https://github.com/storecamera/flutter_package.git
      ref: 9dd7f96b5a50b3b7d2351ee4e31ee3935dd91efc
      path: flutter_sheet_localization
  http: ^0.13.1
  intl: ^0.17.0
  localization_builder: ^0.15.7
  meta: ^1.7.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  build_test: ^2.0.0

