name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  build: ^2.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  csv: ^5.0.0
  dart_style: ^2.0.0
  flutter:
    sdk: flutter
  flutter_sheet_localization:
    git:
      url: https://github.com/storecamera/flutter_package.git
      ref: 717a973898fcc4844f829ec7287861a33cfe669e
      path: flutter_sheet_localization
  http: ^0.13.1
  intl: ^0.17.0
  localization_builder: ^0.15.7
  meta: ^1.3.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.2
  build_test: ^2.0.0
  flutter_lints: ^1.0.4
